safe: false
pygments: true
markdown: rdiscount
permalink: pretty
baseurl: /
url: http://blog.serverhorror.com
x-name: blog.serverhorror.com
google-analytics-id: UA-23535287-4
flattr-user: serverhorror
twitter-user: serverhorror

