---
layout: post
title: Monitoring Thoughts
categories: []
tags:
- Hardware
- JSON
- linux
- Monitoring
- NimSoft
- Server
- Site Management
- Web Design and Development
status: publish
type: post
published: true
meta:
  reddit: a:2:{s:5:"count";s:1:"0";s:4:"time";s:10:"1322875045";}
  _wpas_skip_twitter: '1'
  _wpas_skip_fb: '1'
  _wpas_skip_linkedin: '1'
author: 
---
<div class="posterous_autopost">
<h1>Monitoring Thoughts</h1>
<p>How would you scale monitoring and how would you ensure that with hundreds of thousands of events per minute you’ll still get the important ones?</p>
<p><strong>A lot</strong> of stuff is missing here. This is merely a note how I think a scaling architecture for monitoring should look like. Also one should be able to do math on the events!</p>
<h2>On Agents</h2>
<p><strong>RULE</strong>: <em>events generated by Agents are stateless</em></p>
<ol>
<li>Run a monitoring agent on each node!</li>
<li>Each agent performs a number of <em>tasks</em>These are specifically called tasks since those are not necessarily checks. Also <strong>I associate</strong> checks with <em>nagios checks</em>. It’s not what we want to do!
<p>A task does one thing, and one thing only:</p>
<ul>
<li>do not create tasks that are what <a class="zem_slink" title="Nimsoft" href="http://en.wikipedia.org/wiki/Nimsoft" rel="wikipedia">NimSoft</a> does (CMD – CPU/Memory/Disk)</li>
</ul>
</li>
<li>Each tasks generates an event
<ul>
<li>Everything is an event!</li>
<li>A successful task just a taks that ran without (programmatical errors)</li>
<li>A failed task is something where a programmatical error occured!</li>
</ul>
</li>
<li>Create a <a class="zem_slink" title="JSON" href="http://en.wikipedia.org/wiki/JSON" rel="wikipedia">JSON</a> String from the event</li>
<li>Submit the JSON string to some messaging middleware (preferrably <a class="zem_slink" title="RabbitMQ" href="http://en.wikipedia.org/wiki/RabbitMQ" rel="wikipedia">RabbitMQ</a>)</li>
</ol>
<h2>On Middleware</h2>
<ol>
<li><a class="zem_slink" title="Message" href="http://en.wikipedia.org/wiki/Message" rel="wikipedia">Messages</a>must be persistent
<ul>
<li>It is safe to restart the <a class="zem_slink" title="Server (computing)" href="http://en.wikipedia.org/wiki/Server_%28computing%29" rel="wikipedia">server</a>!</li>
</ul>
</li>
<li>What are just messages to the middleware are the guts of the system.Those are the events generated by agents</li>
</ol>
<h2>On Servers</h2>
<p>There are 2 kinds of servers:</p>
<ul>
<li><a class="zem_slink" title="Persistence (computer science)" href="http://en.wikipedia.org/wiki/Persistence_%28computer_science%29" rel="wikipedia">Persistence</a>ServersThese run somewhere in a rack. They will grab one event after another from a queue and store them in a safe place for later reference.
<p>Once a <em>Persistence <a class="zem_slink" title="File server" href="http://en.wikipedia.org/wiki/File_server" rel="wikipedia">Server</a></em> grabbed an event from the queue it is no longer visible to other servers. Each event will reside on and exatly on <em>Persistence Server</em>.</li>
<li><a class="zem_slink" title="Notification system" href="http://en.wikipedia.org/wiki/Notification_system" rel="wikipedia">Notification</a>ServersThese run either on physical serves in a rack and just grab one notification at a time from the messaging middleware.
<ul>
<li>All notification server <em>can</em> retrieve all events.</li>
<li>Notification Servers can subscribe to a certain subset of topics.</li>
</ul>
</li>
<li>There may be a lot of servers. We don’t want our monitoring failing</li>
</ul>
<h2>On Persistence Servers</h2>
<ol>
<li>Subscribe to the global queue</li>
<li>Start grabbing events</li>
<li>Store the event on diskWhat exactly storing means is yet to be determined!</li>
<li>Start over again</li>
</ol>
<h2>On Notification Servers</h2>
<ol>
<li>Subscribe to the notification queue or a topic queue</li>
<li>Start grabbing events</li>
<li>Display the eventWhat exactly displaying means is yet to be determined!</li>
<li>Start over again&nbsp;</li>
</ol>
</div>
